# Generated by Django 4.2.4 on 2023-08-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('driver_id', models.IntegerField()),
                ('status', models.CharField(choices=[('OFF', 'OFF'), ('работает', 'работает')], max_length=50)),
            ],
        ),
    ]
