# Generated by Django 4.2.4 on 2023-08-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlog',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
