# Generated by Django 4.2.4 on 2023-08-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverLog', '0002_alter_driverlog_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlog',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
